name: Integration

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  integrate-test:
    name: Run integrate test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task:
          - endpoint: http://c2.darwinia-rpc.itering.io:9944/
            target-chain-id: 44
          - endpoint: http://c2.crab-rpc.itering.io:9944/
            target-chain-id: 46
          # - endpoint: https://ethereum-sepolia-rpc.publicnode.com
          #   target-chain-id: 421614
          # - endpoint: https://sepolia-rollup.arbitrum.io/rpc
          #   target-chain-id: 11155111
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: yarn.lock
      - name: install dependencies
        run: yarn install

      - name: run task
        env:
          ORMPIPE_LOG_LEVEL: debug
          ORMPIPE_SIGNER: ${{ secrets.ORMPIPE_SIGNER }}
        run: |
          scripts/ormpipe.sh integration \
            send-message-msgport \
            --endpoint=${{ matrix.task.endpoint }} \
            --target-chain-id=${{ matrix.task.target-chain-id }}

