name: Integration

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  integrate-test:
    name: Run integrate test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task:
          - endpoint: https://rpc.darwinia.network
            target-chain-id: 44
          - endpoint: https://crab-rpc.darwinia.network
            target-chain-id: 46
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: yarn.lock
      - name: install dependencies
        run: yarn install

      # - name: run task
      #   env:
      #     ORMPIPE_LOG_LEVEL: debug
      #     ORMPIPE_SIGNER: ${{ secrets.ORMPIPE_SIGNER }}
      #   run: |
      #     scripts/ormpipe.sh integration \
      #       send-message-msgline \
      #       --endpoint=${{ matrix.task.endpoint }} \
      #       --target-chain-id=${{ matrix.task.target-chain-id }}
